# Generated by Django 3.1.1 on 2020-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia_id', models.IntegerField(blank=True, null=True)),
                ('descripcion_cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tlf_extension', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tin_usuarios',
                'managed': False,
            },
        ),
    ]
