# Generated by Django 3.1.1 on 2020-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinDependencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tin_dependencias',
                'managed': False,
            },
        ),
    ]
